import type { Metadata } from "next";
import { Geist as GeistFont, Geist_Mono } from "next/font/google";
import "./globals.css";
import { use } from "react";
import useServerDarkMode from "./hooks/use-server-dark-mode";

const Geist = GeistFont({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    "template": "%s | Finance App",
    "default": "Finance App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = use(useServerDarkMode("dark"));
  return (
    <html lang="en" className={theme}>
      <body
        className={`${Geist.className} min-h-screen flex flex-col px-8`}
      >
        {children}
      </body>
    </html>
  );
}
